backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "teams"
    label: "Teams"
    folder: "content/teams"
    create: true 
    slug: "{{name}}"
    fields:
      - label: "Team name"
        name: "name"
        widget: "string"
      - label: "Team logo"
        name: "logo"
        widget: "image"
      - label: "Creation Date"
        name: "date"
        widget: "datetime"
      - label: Associated team
        name: related_team
        widget: relation
        required: true
        multiple: true
        hint: >-
          The team(s) this member should be a part of
        collection: teams
        valueField: name
        searchFields: ["name"]
        displayFields: ["name"]
  - name: "people"
    label: "People"
    folder: "content/people"
    create: true
    slug: "{{name}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Picture"
        name: "picture"
        widget: "image"
      - label: "Creation Date"
        name: "date"
        widget: "datetime"
