backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "teams"
    label: "Teams"
    folder: "content/teams"
    create: true 
    slug: "{{name}}"
    fields:
      - {label: "Team name", name: "name", widget: "string"}
      - {label: "Team logo", name: "logo", widget: "image"}
      - {label: "Creation Date", name: "date", widget: "datetime"}
